# https://github.com/marketplace/actions/auto-request-review#reviewers-configuration
reviewers:
  defaults:
      - team:qa-team
files:
  '**/*.yaml':
    - team:qa-team
options:
  ignore_draft: false
  number_of_reviewers: 3
  enable_group_assignment: true
