# https://github.com/marketplace/actions/auto-request-review#reviewers-configuration
files:
  '**/*.yaml':
    - AlexTzykin
    - team:qa-team
defaults:
    - AlexTzykin
    - team:qa-team
options:
  ignore_draft: true
  number_of_reviewers: 3
