
patchesStrategicMerge:
- ingress-https.yaml

resources:
- ../platform
- storefront-cm.yaml
- storefront-deploy.yaml
- storefront-service.yaml

configurations:
- varconfig.yaml

vars:
- name: VC_STOREFRONT_SERVICE
  objref:
    kind: Service
    name: storefront
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name    
- name: VC_NAMESPACE
  objref:
    kind: Service
    name: storefront
    apiVersion: v1
  fieldref:
    fieldpath: metadata.namespace
- name: VC_INSTANCE
  objref:
    kind: Service
    name: storefront
    apiVersion: v1
  fieldref:
    fieldpath: metadata.labels.instance