resources:
- ingress-https.yaml
- storefront-cm.yaml
- storefront-deploy.yaml
- storefront-service.yaml

vars:
- name: VC_STOREFRONT_SERVICE
  objref:
    kind: Service
    name: storefront
    apiVersion: v1
  fieldref:
    fieldpath: metadata.name