kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cms-content-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: blob-premium
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi