kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cms-content-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: rook-nfs-share-delete
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi