apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-kit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: prod-tenant
  source:
    path: ui-kit/overlays/demo
    repoURL: https://github.com/VirtoCommerce/vc-deploy-dev
    targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
