kind: ConfigMap
apiVersion: v1
metadata:
  name: platform-cm
  annotations:
    reloader.stakater.com/match: "true"  
data:
  Content__FileSystem__RootPath: /opt/virtocommerce/platform/wwwroot/cms-content
