apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storefront
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: prod-tenant
  source:
    path: storefront-app/overlays/mercury
    repoURL: https://github.com/VirtoCommerce/vc-deploy-dev
    targetRevision: mercury
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
