apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-secret-configmap
  annotations:
    reloader.stakater.com/match: "true" 
data:
    templates-custom.hcl: |
        {{ with secret "secret/notifications" }}
        export Notifications__SendGrid__ApiKey="{{ .Data.apikey }}"
        {{ end }}
        {{ with secret "secret/notifications" }}
        export Notifications__Smtp__Password="{{ .Data.password }}"
        {{ end }}
        {{ with secret "secret/b2b-qa-sso" }}
        export AzureAd__ApplicationId="{{ .Data.ApplicationID }}"
        {{ end }}
        {{ with secret "secret/b2b-qa-sso" }}
        export AzureAd__TenantId="{{ .Data.TenantID }}"
        {{ end }}
        {{ with secret "secret/b2b-qa-twilio" }}
        export Notifications__Twilio__AccountId="{{ .Data.NotificationsTwilioAccountId }}"
        {{ end }}
        {{ with secret "secret/b2b-qa-twilio" }}
        export Notifications__Twilio__AccountPassword="{{ .Data.NotificationsTwilioAccountPassword }}"
        {{ end }}
        {{ with secret "secret/b2b-qa-authorize-net" }}
        export Payments__AuthorizeNet__ApiLogin="{{ .Data.PaymentsAuthorizeNetApiLogin }}"
        {{ end }}
        {{ with secret "secret/b2b-qa-authorize-net" }}
        export Payments__AuthorizeNet__SHA2Hash="{{ .Data.PaymentsAuthorizeNetSHA2Hash }}"
        {{ end }}
        {{ with secret "secret/b2b-qa-authorize-net" }}
        export Payments__AuthorizeNet__TxnKey="{{ .Data.PaymentsAuthorizeNetTxnKey }}"
        {{ end }}
        {{ with secret "secret/b2b-qa-tax-avalara" }}
        export Tax__Avalara__AccountNumber="{{ .Data.TaxAvalaraAccountNumber }}"
        {{ end }}
        {{ with secret "secret/b2b-qa-tax-avalara" }}
        export Tax__Avalara__LicenseKey="{{ .Data.TaxAvalaraLicenseKey }}"
        {{ end }}

