apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  revisionHistoryLimit: 2
  replicas: 2
  template:
    metadata:
      annotations:
        reloader.stakater.com/search: "true"
        configmap.reloader.stakater.com/reload: "regression-platform-cm, regression-deployment-cm, regression-platform-secret-configmap"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-configmap: "regression-platform-secret-configmap"
        vault.hashicorp.com/agent-requests-cpu: "25m"
        vault.hashicorp.com/agent-limits-cpu: "50m"   
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "myapp"
    spec:
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      initContainers:
        - name: init-sqldatabase
          image: mcr.microsoft.com/mssql-tools
          env:
            - name: VC_SAMPLE_DATA_DB
              value: regression-platform_qa_source
            - name: VC_DB_COPY_PARAM
              value: "AS COPY OF [$(VC_SAMPLE_DATA_DB)]"  

        - name: init-platform
          image: ghcr.io/virtocommerce/vc-deploy-containers/vc-build-image:stable
          command: ["/root/.dotnet/tools/vc-build", "InstallModules"]
#          "InstallModules -DiscoveryPath /mnt/Modules -PackageManifestPath /mnt/config/vc-package.json -SkipDependencySolving"
          args: []
          volumeMounts:
          - mountPath: /mnt/Modules
            name: modules-data
          - mountPath: /mnt/config
            name: vc-package
            readOnly: true

      containers:
        - name: vc-platform-web
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1024Mi"
          volumeMounts:
            - mountPath: "/opt/virtocommerce/platform/wwwroot/cms-content"
              name: cms-content-data
            - mountPath: "/opt/virtocommerce/platform/modules"
              name: modules-data
            - mountPath: "/opt/virtocommerce/platform/shared"
              name: shared   
      volumes:
      - name: shared
        persistentVolumeClaim:
          claimName: shared-volume
      - name: cms-content-data
        persistentVolumeClaim:
          claimName: cms-content-volume
      - name: modules-data
        emptyDir: {}  
      - name: vc-package
        configMap:
          name: deployment-cm
          items:
          - key: vc-package.json
            path: vc-package.json
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate 
