kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Mi
  storageClassName: "rook-nfs-share-delete"