apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-secret-configmap
  annotations:
    reloader.stakater.com/match: "true" 
data:
    templates-custom.hcl: |
        {{ with secret "secret/redis" }}
        export ConnectionStrings__RedisConnectionString=redis-master.redis:6379,password={{ .Data.REDIS_PASS }},ssl=False,abortConnect=False
        {{ end }} 
 
