kind: ConfigMap
apiVersion: v1
metadata:
  name: platform-cm
data:
  Notifications__DefaultSender: "azure_25da07ed75daacae20578a7a7dc58541@azure.com"
  Notifications__Gateway: "SendGrid"
  Notifications__SmsDefaultSender: "+17012510519"
  Notifications__Smtp__EnableSsl: "False"
  Notifications__Smtp__Host: "smtp.sendgrid.net"
  Notifications__Smtp__Login: "apikey"
  Notifications__Smtp__Port: "587"
  Notifications__SmsGateway: "Twilio"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "false"
  AppInsights__EnableDependencyTrackingTelemetryModule: "false"
  Swagger__UI__Enabled: "true"
  PushNotifications__ForceWebSockets: "true"
  PushNotifications__ScalabilityMode: "RedisBackplane"
  PushNotifications__HubUrl: "https://$(VC_PLATFORM_SERVICE).$(VC_NAMESPACE).govirto.com/pushNotificationHub"
  PushNotifications__RedisBackplane__ChannelName: "$(VC_PLATFORM_SERVICE)-$(VC_NAMESPACE)-chanel"
  Search__ElasticSearch__Server: https://elasticsearch-dev.govirto.com
  AzureAd__Enabled: "true"
  AzureAd__Priority: "1"
  AzureAd__AuthenticationType: "AzureAD"
  AzureAd__ApplicationId: "8227d950-975c-4c28-b7d4-ea440a59dcbb"
  AzureAd__TenantId: "bc03e660-5e3a-45c4-bf5c-b75489f78923"
  PasswordLogin__Enabled: "true" 
  PasswordLogin__Priority: "0"
  Search__Scope: "$(VC_PLATFORM_SERVICE)$(VC_NAMESPACE)-new-index"
  Content__FileSystem__PublicUrl: https://$(VC_PLATFORM_SERVICE).$(VC_NAMESPACE).govirto.com/cms-content/
  Assets__FileSystem__PublicUrl: https://$(VC_PLATFORM_SERVICE).$(VC_NAMESPACE).govirto.com/cms-content/assets/
  VirtoCommerce__LicenseFilePath: app_data/VirtoCommerce.lic
  VirtoCommerce__LicensePublicKeyPath: app_data/public.key
  VirtoCommerce__LicensePrivateKeyPath: app_data/private.key
  VirtoCommerce__LocalUploadFolderPath: app_data/uploads
  VirtoCommerce__Hangfire__JobStorageType: SqlServer
  Logging__LogLevel__Default: "Information"
  Search__OrderFullTextSearchEnabled: "true"
 #Setting for authorizenet
  Payments__AuthorizeNet__ApiLogin: "8hPT4p99R"
  Payments__AuthorizeNet__SHA2Hash: "FA6D2B37A7E9105942D2D184F1B2DBD8D9CA85611DE55B2267A6F7E0D7E49ACD9A6BC238CE068E75CA14ACFAD734F700FD94DCAB20353DD4D32D9BABE72DBBE4"
  Payments__AuthorizeNet__TxnKey: "63c54EWq5d2XnGAR"
 #Search__Provider: AzureSearch
  Search__AzureSearch__SearchServiceName: qa-demovc-3-search
  Search__AzureSearch__Key: 6BE1143312E89C26C227E6BBAE24DD47
# Search__Provider: Lucene
# Search__Scope: "regression"
# Settings for avatax
  Tax__Avalara__AccountNumber: "2000188799"
  Tax__Avalara__LicenseKey: "16BC3F87E836E15C" 
#Active Directory
  AzureAd__Enabled: "false"
  PasswordLogin__Enabled: "true"
  DefaultMainMenuState__items: |
    [
      {
      "path": "browse/marketing",
      "isFavorite": "true",
      "order": 0
      }, 
      {
      "path": "browse/catalog",
      "isFavorite": "true",
      "order": 1
      }
    ]
