kind: ConfigMap
apiVersion: v1
metadata:
  name: platform-cm
data:
# headers
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
  AppInsights__EnableDependencyTrackingTelemetryModule: "false"
#setting for swagger
  Swagger__UI__Enabled: "false"
# Setting for redis
  PushNotifications__ForceWebSockets: "true"
  PushNotifications__ScalabilityMode: "RedisBackplane"
  PushNotifications__HubUrl: "https://$(VC_PLATFORM_SERVICE).$(VC_NAMESPACE).govirto.com/pushNotificationHub"
  PushNotifications__RedisBackplane__ChannelName: "$(VC_PLATFORM_SERVICE)-$(VC_NAMESPACE)-chanel"
# Search settings
  Search__Scope: "$(VC_PLATFORM_SERVICE)$(VC_NAMESPACE)-new-index"
  Search__OrderFullTextSearchEnabled: "true"
# Elastic Search settings
  Search__ElasticSearch__Server: https://elasticsearch-dev.govirto.com
# Elastic App Search settings
# Search__Provider: "ElasticAppSearch"
  Search__ElasticAppSearch__Endpoint: https://enterprise-search-test.govirto.com
  Search__ElasticAppSearch__EnableHttpCompression: "true"
# End of search settings
  AzureAd__Enabled: "true"
  AzureAd__ApplicationId: "86d04c35-143d-4d3c-aea2-8608e2186282"
  AzureAd__TenantId: "common"
  AzureAd__ValidateIssuer: "MultitenantAzureAD"
# storage 
  Content__FileSystem__PublicUrl: https://$(VC_PLATFORM_SERVICE).$(VC_NAMESPACE).govirto.com/cms-content/
  Assets__FileSystem__PublicUrl: https://$(VC_PLATFORM_SERVICE).$(VC_NAMESPACE).govirto.com/cms-content/assets/
# license settings
  VirtoCommerce__LicenseFilePath: app_data/VirtoCommerce.lic
  VirtoCommerce__LicensePublicKeyPath: app_data/public.key
  VirtoCommerce__LicensePrivateKeyPath: app_data/private.key
  VirtoCommerce__Licensing__LicensePrivateKeyPath: "/opt/virtocommerce/platform/license/VirtoCommerce.lic"
  VirtoCommerce__LocalUploadFolderPath: app_data/uploads
  VirtoCommerce__Hangfire__JobStorageType: SqlServer
  Logging__LogLevel__Default: "Information"
# setting for authorize.net
  Payments__AuthorizeNet__ApiLogin: "8hPT4p99R"
  Payments__AuthorizeNet__SHA2Hash: "FA6D2B37A7E9105942D2D184F1B2DBD8D9CA85611DE55B2267A6F7E0D7E49ACD9A6BC238CE068E75CA14ACFAD734F700FD94DCAB20353DD4D32D9BABE72DBBE4"
  Payments__AuthorizeNet__TxnKey: "63c54EWq5d2XnGAR"
  ASPNETCORE_ENVIRONMENT: "Production"
# Notifications__DefaultSender: ""
# Notifications__Gateway: "SendGrid"
# Notifications__SmsDefaultSender: "+17012510519"
# Notifications__Smtp__EnableSsl: "False"
# Notifications__Smtp__Host: "smtp.sendgrid.net"
# Notifications__Smtp__Login: "apikey"
# Notifications__Smtp__Port: "587"
# default menu state 
  DefaultMainMenuState__items__0__path: "browse/marketing"
  DefaultMainMenuState__items__0__isFavorite: "true"
  DefaultMainMenuState__items__0__order: "1"
  VirtoCommerce__ApplicationInsights__SamplingOptions__Processor: "Fixed"
