apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-secret-configmap
  annotations:
    reloader.stakater.com/match: "true" 
data:
    templates-custom.hcl: |
        {{ with secret "secret/redis" }}
        export ConnectionStrings__RedisConnectionString=redis-master.redis:6379,password={{ .Data.REDIS_PASS }},ssl=False,abortConnect=False
        {{ end }}
        {{ with secret "secret/search/elastic-app-search" }}
        export Search__ElasticAppSearch__PrivateApiKey={{ .Data.PrivateApiKey }}
        {{ end }}
        {{ with secret "secret/license" }}
        export VC_LICENSE={{ .Data.platform }}
        {{ end }} 
