apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcplatform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: qa
    server: 'https://aks-f783f1e0.hcp.westus.azmk8s.io:443'
  project: tenant
  source:
    path: platform-dev/overlays/qa
    repoURL: https://github.com/VirtoCommerce/vc-deploy-dev
    targetRevision: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
