apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storefront
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: qa
    server: 'https://kubernetes.default.svc'
  project: tenant
  source:
    path: storefront-app/overlays/qa
    repoURL: https://github.com/VirtoCommerce/vc-deploy-dev
    targetRevision: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
