apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-ui-kit
spec:
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ui-kit
  replicas: 1
  template:
    metadata:
      labels:
        app: ui-kit
    spec:
      containers:
      - name: ui-kit
        image: ghcr.io/virtocommerce/platform-ui-kit:0.0.3
        env:
          - name: PLATFORM_URL
            value: "https://$(VC_PLATFORM_SERVICE).$(VC_NAMESPACE).govirto.com"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 64Mi
          limits:
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ui-kit
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: ui-kit
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ui-kit-ingress-https
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:   
      - "ui-kit.govirto.com"
      secretName: $(VC_INSTANCE)-ui-kit-$(VC_NAMESPACE)-tls
  rules:
  - host: ui-kit.govirto.com
    http:
      paths:
      - backend:
          serviceName: ui-kit
          servicePort: 80
        path: /