apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-secret-configmap
  annotations:
    reloader.stakater.com/match: "true" 
data:
    templates-base.hcl: |
        {{ with secret "secret/webstore-sso" }}
        export AzureAd__ApplicationId={{ .Data.ApplicationID }}
        {{ end }}
        {{ with secret "secret/webstore-sso" }}
        export AzureAd__TenantId={{ .Data.TenantID }}
        {{ end }}
        {{ with secret "secret/redis" }}
        export ConnectionStrings__RedisConnectionString=redis-master.redis:6379,password={{ .Data.REDIS_PASS }},ssl=False,abortConnect=False,channelPrefix=$(VC_PLATFORM_SERVICE)-$(VC_NAMESPACE)-chanel
        {{ end }} 
        {{ with secret "secret/mssql" }}
        export ConnectionStrings__VirtoCommerce="Server=tcp:vc-dev-dbserver.database.windows.net,1433;Database=loadtest-platform_dev_separate;User ID=virto@vc-dev-dbserver;Password={{ .Data.db_password }};Trusted_Connection=False;Encrypt=True;TrustServerCertificate=True;"
        {{ end }}

