apiVersion: v1
kind: ConfigMap
metadata:
  name: storefront-secret-configmap
  annotations:
    reloader.stakater.com/match: "true" 
data:
    templates-custom.hcl: |
        {{ with secret "secret/loadtest/endpoint" }}
        export VirtoCommerce__Endpoint__UserName={{ .Data.UserName }}
        {{ end }}
        {{ with secret "secret/loadtest/endpoint" }}
        export VirtoCommerce__Endpoint__Password={{ .Data.Password }}
        {{ end }}