kind: ConfigMap
apiVersion: v1
metadata:
  name: deployment-cm
  annotations:
    reloader.stakater.com/match: "true"
data:
  ELECTRONICS_THEME_URL: https://github.com/VirtoCommerce/vc-theme-default/releases/download/2.1.13/vc-theme-default-2.1.13.zip
  ELECTRONICS_THEME_LOCATION: /mnt/cms-content/Themes/Electronics
  B2B_THEME_URL: https://github.com/VirtoCommerce/vc-theme-b2b/releases/download/3.0.8/vc-b2b-theme-3.0.8.zip
  B2B_THEME_LOCATION: /mnt/cms-content/Themes/B2B-store
 #MERCURY_THEME_URL: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.1.0-pr-143-458ab7e3.zip
 #MERCURY_THEME_LOCATION: /mnt/cms-content/Themes/B2B-store
  ASSETS_URL: https://vcbacpac.blob.core.windows.net/dac-packages/webstore_assets_4.zip
  ASSETS_LOCATION: /mnt/cms-content/assets