name: DEV demoVC 3 to Azure

on:
  workflow_dispatch:
  push:
    paths:
      - 'vc-package.json'
    branches: [ qa, dev ]

jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AZURE_PLATFORM_NAME: dev-demovc3-admin  # set this to your application's name
      AZURE_PLATFORM_PACKAGE_PATH: '${{ github.workspace }}/backend'  # set this to the path to your web app project, defaults to the repository root
      AZURE_STOREFRONT_NAME: dev-demovc3-store  # set this to your application's name
      AZURE_STOREFRONT_PACKAGE_PATH: '${{ github.workspace }}/storefront'  # set this to the path to your web app project, defaults to the repository root

    steps:

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install VirtoCommerce.GlobalTool
        run: dotnet tool update -g virtocommerce.globaltool

      - name: Install Platform and Modules
        working-directory: ${{ env.AZURE_PLATFORM_PACKAGE_PATH }}
        run: vc-build install -PackageManifestPath ../vc-package.json -SkipDependencySolving

      - name: Deploy Platform to Azure
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
        with:
          app-name: ${{ env.AZURE_PLATFORM_NAME }}
          publish-profile: ${{ secrets.AZURE_PLATFORM_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_PLATFORM_PACKAGE_PATH }}
