name: Cloud platform deployment

on:
  workflow_dispatch:
  push:
    paths:
      - 'backend/**'
    branches: [ virtooz ]

jobs:
  gitops:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install vc-build
      run: |
        dotnet tool install --global VirtoCommerce.GlobalTool

    - name: Pack
      run: |
        vc-build install -PackageManifestPath ./backend/packages.json -ProbingPath ./backend/platform/app_data/modules -DiscoveryPath ./backend/platform/modules --root ./backend/platform -SkipDependencySolving

    - name: Get platform version
      id: platform-version
      run: |
        echo "PLATFORM_VERSION=$(cat ./backend/packages.json | jq -r '.PlatformVersion')" >> $GITHUB_ENV

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Prepare files for Docker image
      run: |
        curl -sSL -o ./backend/Dockerfile https://github.com/VirtoCommerce/vc-docker/raw/refs/heads/feat/net10/linux/platform/Dockerfile
        curl -sSL -o ./wait-for-it.sh https://github.com/VirtoCommerce/vc-docker/raw/refs/heads/feat/net10/linux/platform/wait-for-it.sh
        mkdir ./publish
        mv ./backend/platform/* ./publish

    - name: Build and Publish Docker Image to Virto container registry
      run: |
        vc-build BuildAndPush -DockerUsername $DOCKER_LOGIN -DockerPassword $DOCKER_PASSWORD -DockerfilePath $DOCKERFILE_PATH -DockerImageName $IMAGE_REPOSITORY -DockerImageTag $TAG -DockerRegistryUrl $CONTAINER_REGISTRY
      env:
        DOCKER_LOGIN: vcpt-repo-saccess
        DOCKER_PASSWORD: ${{ secrets.VCPT_ACR_DOCKER_PASSWORD }}
        DOCKERFILE_PATH: ./backend/Dockerfile
        CONTAINER_REGISTRY: virtopaasregistrymain.azurecr.io
        IMAGE_REPOSITORY: virtopaasregistrymain.azurecr.io/vcpt/virtooz-platform
        TAG: ${{ env.PLATFORM_VERSION }}-${{ steps.vars.outputs.sha_short }}

    - name: Update app
      run: |
        vc-build CloudEnvSetParameter -EnvironmentName vcpt-virtooz -CloudToken ${{ secrets.VCPT_PLATFORM_TOKEN }} -HelmParameters platform.image.tag=$TAG
      env:
        TAG: ${{ env.PLATFORM_VERSION }}-${{ steps.vars.outputs.sha_short }}
