name: Cloud storybook deployment

on:
  workflow_dispatch:
  push:
    paths:
      - 'storybook/**'
    branches: 
      - 'vcst-*'

jobs:
  gitops:
    runs-on: ubuntu-latest
    env:
      ARGO_APP_NAME: ${{ github.ref_name }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install vc-build
      run: |
        dotnet tool install --global VirtoCommerce.GlobalTool --version 3.4.1
    
    - name: Get storybook version
      id: platform-version
      run: |
        echo "STORYBOOK_TAG=$(cat ./storybook/image.json | jq -r '.Tag')" >> $GITHUB_ENV
        echo "STORYBOOK_REPO=$(cat ./storybook/image.json | jq -r '.Repository')" >> $GITHUB_ENV
      
    - name: Docker
      run: |
        docker login virtopaasregistrymain.azurecr.io -u vcst-token -p ${{ secrets.VCST_ACR_DOCKER_PASSWORD }}
        docker pull $STORYBOOK_REPO:$STORYBOOK_TAG
        docker tag $STORYBOOK_REPO:$STORYBOOK_TAG virtopaasregistrymain.azurecr.io/vcst/storybook:$STORYBOOK_TAG
        docker push virtopaasregistrymain.azurecr.io/vcst/storybook:$STORYBOOK_TAG

    - name: Update app
      run: |
        vc-build SetHelmParameter -ArgoServer https://argo.virtocommerce.cloud -ArgoAppName ${{ env.ARGO_APP_NAME }} -ArgoToken ${{ secrets.VCST_TOKEN }} -HelmParameters customApps.app1.image.tag=$TAG
      env:
        TAG: ${{ env.STORYBOOK_TAG }}