name: Run loadtest

on:
  workflow_dispatch:
  pull_request:
      branches: [ loadtest ]
  
jobs:
    loadtest:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      - name: Echo
        id: echo
        run: |
            echo start
