#
name: DEV-demoVC-3 to azure

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    paths:
      - 'vc-package.json'
    branches: [ qa, dev ]

env:
  AZURE_PLATFORM_NAME: dev-demovc3-admin  # set this to your application's name
  AZURE_PLATFORM_PACKAGE_PATH: '${{ github.workspace }}/platform'  # set this to the path to your web app project, defaults to the repository root

  AZURE_STOREFRONT_NAME: dev-demovc3-store  # set this to your application's name
  AZURE_STOREFRONT_PACKAGE_PATH: '${{ github.workspace }}/storefront'  # set this to the path to your web app project, defaults to the repository root


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install VirtoCommerce.GlobalTool
        run: dotnet tool update -g virtocommerce.globaltool

      - name: Get Image Version
        uses: VirtoCommerce/vc-github-actions/get-image-version@master
        id: image

      - name: Install Platform and Modules
        working-directory: ${{ github.workspace }}/platform
        run: vc-build install -PackageManifestPath ../vc-package.json -SkipDependencySolving

      - name: Deploy Platform to Azure
        uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
        with:
          app-name: ${{ env.AZURE_PLATFORM_NAME }}
          publish-profile: ${{ secrets.AZURE_PLATFORM_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_PLATFORM_PACKAGE_PATH }}

      # - name: Deploy Storefront to Azure
      #   uses: azure/webapps-deploy@0b651ed7546ecfc75024011f76944cb9b381ef1e
      #   with:
      #     app-name: ${{ env.AZURE_STOREFRONT_NAME }}
      #     publish-profile: ${{ secrets.AZURE_STOREFRONT_PUBLISH_PROFILE }}
      #     package: ${{ env.AZURE_STOREFRONT_PACKAGE_PATH }}
