name: Run performance

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: 3.11.4
      serverDB: ${{ secrets.PS_SERVERDB }}
      nameDB: ${{ secrets.PS_DBNAME }}
      usernameDB: ${{ secrets.PS_USERNAME }}
      passwordDB: ${{ secrets.PS_DBPASS }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        architecture: x64

    - name: Install project dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ./scripts/performance

    - name: Run #
      run: |
        python scriptDB.py
      working-directory: ./scripts/performance